[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version = "2.1.6", features = ["sqlite"]}
rocket = "0.5.0"
sqlite = "0.36.0"
sqlx = "0.7.4"
